### ISSUE TITLE
[REQ] Update Vidtodo.com/thevideo.me/vidup.me/estream.to/nowvideo.sx/movshare.net/streamin.to/playedto.me/gorillavid.in/daclips.in/vshare.eu/vidto.me Support

### ISSUE THREAD

**Issue by stormr2010** [Twoure/UnSupportedServices.bundle#5]
Hi Twoure,

I have gone through and tested a few sources that are no longer working.

These are:
Vidtodo.com
thevideo.me
vidup.me
estream.to
nowvideo.sx
movshare.net
streamin.to
playedto.me
gorillavid.in
daclips.in
vshare.eu
vidto.me

Can you please provide an update to these services?

thanks again for your time and effort.

**Comment by Twoure** [comment]
### Fix progress:

- [x]  Vidtodo.com _(https://github.com/Twoure/UnSupportedServices.bundle/commit/98399d6fcdee10772926ab1bed430e55f3352aee)_
- [ ] ~~thevideo.me~~ _(already fixed in https://github.com/Twoure/UnSupportedServices.bundle/commit/164783fc039a2f8649855f65e924c07f614609d1)_
- [x] vidup.me _(https://github.com/Twoure/UnSupportedServices.bundle/commit/92765517916554bf0bc230080d4357bce6533a8f)_
- [ ] ~~estream.to~~ _(already fixed in https://github.com/Twoure/UnSupportedServices.bundle/commit/5cf67e092aedb2d214034735293220af58d8ee3b)_
- [ ] ~~nowvideo.sx~~ _(nothing to change: their servers can be too slow for PMS, so YMMV)_
- [x] movshare.net _(https://github.com/Twoure/UnSupportedServices.bundle/commit/048150e2a78f973353245fea9080d1768315f45d)_
- [x] streamin.to _(https://github.com/Twoure/UnSupportedServices.bundle/commit/2e0fb0d83ec8fa15ede400782eb2bf0b1e9d6b18)_
- [ ] ~~playedto.me~~ _(host is migrating to `golocker.to` https://github.com/Twoure/UnSupportedServices.bundle/commit/74b43e4505aa3f97e3adb4814a0ec8c7a03fe22d)_
- [ ] ~~gorillavid.in~~ _(already fixed in https://github.com/Twoure/UnSupportedServices.bundle/commit/1ddbba94a404d0ce07fd8646d010c1283858b778)_
- [ ] ~~daclips.in~~ _(nothing to change: online videos play fine)_
- [x] vshare.eu _(fixed, but their streams timeout in PMS, so YMMV https://github.com/Twoure/UnSupportedServices.bundle/commit/b901c08f2e4c15f2d862e23f6a8ad03db2ef6cff)_
- [x] vidto.me _(https://github.com/Twoure/UnSupportedServices.bundle/commit/e5998fd726c016f31c2cf512ed1db1685b805999)_

**Comment by Twoure** [comment]
Merged `dev` branch changes into `master`.  Refer to https://github.com/Twoure/UnSupportedServices.bundle/issues/5#issuecomment-302910828 for more info.

**Comment by stormr2010** [comment]
Thanks Twoure. I will further test a few more sources and come back with the results

Thanks again
