### ISSUE TITLE
[REQ] Update streamplay.to/vidlox.tv/speedvid.net/watchers.to Support

### ISSUE THREAD

**Issue by stormr2010** [Twoure/UnSupportedServices.bundle#6]
Hi Twoure,

Just another update of some further Source testing

The first list are now confirmed all working - Thanks for your time and effort

I have also found the following sources that require source support update

streamplay.to
vidlox.tv
speedvid.net
watchers.to

I believe this concludes my testing

Thanks again Twoure :)

**Comment by Twoure** [comment]
### Fix progress:

- [x] streamplay.to _(https://github.com/Twoure/UnSupportedServices.bundle/commit/24a2d764cdf6d521495ddf700ac53be4138f45b9)_
- [x] vidlox.tv _(https://github.com/Twoure/UnSupportedServices.bundle/commit/33aeb93b3a338ff17902b9341bc0059cc1884df8)_
- [x] speedvid.net _(https://github.com/Twoure/UnSupportedServices.bundle/commit/a40455d58c307dadf442fb16444e3e47fdecda40)_
- [ ] ~~watchers.to~~ _(Removed in https://github.com/Twoure/UnSupportedServices.bundle/commit/4f81321e9d28d31f45710f58ecd0fe1314347138 due to `Referer` required to play videos)_

**Done:** _06/06/2017_

**Comment by stormr2010** [comment]
vidlox.tv (33aeb93) Tested and confirmed working
